"""create ip_ranges table

Revision ID: 5bb4d895f9b6
Revises: 
Create Date: 2026-07-02 13:55:16.701079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb4d895f9b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ip_version', sa.Integer(), nullable=True),
    sa.Column('network_int', sa.Integer(), nullable=True),
    sa.Column('broadcast_int', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidr', 'provider', name='uq_cidr_provider')
    )
    op.create_index('idx_range', 'ip_ranges', ['network_int', 'broadcast_int'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_range', table_name='ip_ranges')
    op.drop_table('ip_ranges')
    # ### end Alembic commands ###
